import { ApprovalStatus, DiscountType, ListingType } from "@buzzystores/types";

export type AiAgentType =
  | "vendor-intake"
  | "catalogue-builder"
  | "storefront-copy"
  | "campaign"
  | "translation"
  | "support"
  | "vendor-health";

export type AiDraftRequest = {
  agentType: AiAgentType;
  sourceInput: Record<string, unknown>;
  locale?: "en" | "sv";
  promptVersion: string;
};

export type AiDraftResult = {
  provider: string;
  model: string;
  output: Record<string, unknown>;
  confidence?: number;
  requiresHumanApproval: true;
};

export interface AiProvider {
  readonly name: string;
  createDraft(request: AiDraftRequest): Promise<AiDraftResult>;
}

export class MockAiProvider implements AiProvider {
  readonly name = "mock";

  async createDraft(request: AiDraftRequest): Promise<AiDraftResult> {
    if (request.agentType === "vendor-intake") {
      return {
        provider: this.name,
        model: "mock-vendor-intake-v1",
        confidence: 0.82,
        requiresHumanApproval: true,
        output: createVendorIntakeDraft(request.sourceInput)
      };
    }

    if (request.agentType === "catalogue-builder") {
      return {
        provider: this.name,
        model: "mock-catalogue-builder-v1",
        confidence: 0.76,
        requiresHumanApproval: true,
        output: createCatalogueDraft(String(request.sourceInput.productText ?? ""))
      };
    }

    if (request.agentType === "campaign") {
      return {
        provider: this.name,
        model: "mock-campaign-draft-v1",
        confidence: 0.74,
        requiresHumanApproval: true,
        output: createCampaignDraft(request.sourceInput)
      };
    }

    return {
      provider: this.name,
      model: "mock-local-draft",
      confidence: 0.7,
      requiresHumanApproval: true,
      output: {
        agentType: request.agentType,
        summary: "Draft generated by the mock provider for review.",
        missingFields: [],
        sourceInput: request.sourceInput
      }
    };
  }
}

function createCampaignDraft(input: Record<string, unknown>): Record<string, unknown> {
  const vendor = isRecord(input.vendor) ? input.vendor : {};
  const vendorName = String(vendor.name ?? input.vendorName ?? "Local vendor");
  const campaignType = String(input.campaignType ?? "WEEKEND_OFFER")
    .toLowerCase()
    .replace(/_/g, " ");
  const listings = Array.isArray(input.approvedListings)
    ? input.approvedListings.filter(isRecord)
    : [];
  const selectedListings = listings.slice(0, 3).map((listing) => String(listing.id ?? listing.title));
  const language = String(input.language ?? input.targetLanguage ?? "en");
  const today = new Date("2026-07-10T09:00:00.000Z");
  const endDate = new Date(today);
  endDate.setDate(today.getDate() + 7);
  const discountValue = campaignType.includes("loyalty") ? 10 : 15;

  return {
    title: `${vendorName} ${titleCase(campaignType)}`,
    description:
      language === "sv"
        ? `${vendorName} kan lansera ett lokalt erbjudande för kunder som handlar via QR-butiken.`
        : `${vendorName} can launch a local offer for customers ordering through the QR storefront.`,
    offerText: `${discountValue}% off selected pickup favourites`,
    suggestedListings: selectedListings,
    suggestedDiscount: {
      type: DiscountType.PERCENTAGE,
      value: discountValue
    },
    whatsappCopy: `${vendorName}: ${discountValue}% off this week. Order from the QR storefront.`,
    instagramCaption: `${vendorName} local offer is live. Tap the QR storefront and order for pickup.`,
    smsCopy: `${vendorName}: use the QR storefront for ${discountValue}% off selected items.`,
    qrPosterHeadline: `${vendorName} offer`,
    qrPosterSubtext: `Scan to order and use the campaign code at pickup checkout.`,
    recommendedStartDate: today.toISOString(),
    recommendedEndDate: endDate.toISOString()
  };
}

function createVendorIntakeDraft(input: Record<string, unknown>): Record<string, unknown> {
  const businessName = String(input.businessName ?? input.name ?? "Local vendor");
  const categoryHint = String(input.categoryHint ?? input.categoryLabel ?? "Local Commerce");
  const description = String(input.description ?? "");
  const missingFields = ["email", "address", "city", "country", "openingHoursText", "productText"].filter(
    (field) => !input[field],
  );
  const trustFlags = [
    input.websiteUrl ? "WEBSITE_PROVIDED" : undefined,
    input.instagramUrl || input.facebookUrl ? "SOCIAL_PROFILE_PROVIDED" : undefined,
    input.phone ? "PHONE_PROVIDED" : undefined
  ].filter(Boolean);

  return {
    suggestedStorefrontHeadline: `${businessName} is getting ready on BuzzyStores`,
    suggestedShortDescription:
      description || `A ${categoryHint.toLowerCase()} vendor preparing a QR-ready storefront.`,
    suggestedLongDescription:
      description ||
      `${businessName} is setting up a local commerce storefront for orders, pickup, bookings, campaigns, and repeat customers.`,
    suggestedCategories: [categoryHint, "Local Commerce"],
    missingFields,
    trustFlags,
    recommendedNextAction:
      missingFields.length > 0
        ? `Collect ${missingFields.slice(0, 3).join(", ")} before admin approval.`
        : "Review AI drafts and submit the storefront for admin approval.",
    suggestedFirstCampaign: `Launch a first-week offer for ${businessName}.`
  };
}

function createCatalogueDraft(productText: string): Record<string, unknown> {
  return {
    listings: parseProductText(productText).map((item) => ({
      title: item.title,
      listingType: ListingType.FOOD_MENU_ITEM,
      price: item.price,
      currency: item.currency,
      shortDescription: "A ready-to-order food item from the vendor.",
      suggestedCategory: "Food & Restaurants",
      tags: ["food", "takeaway", "local"],
      approvalStatus: ApprovalStatus.AI_GENERATED
    }))
  };
}

function parseProductText(productText: string): Array<{ title: string; price: number; currency: string }> {
  return productText
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const match = line.match(/^(.*?)(?:\s+)(\d+(?:[.,]\d{1,2})?)\s*(kr|sek|SEK|EUR|USD)?$/);

      if (!match) {
        return {
          title: line,
          price: 0,
          currency: "SEK"
        };
      }

      return {
        title: String(match[1]).trim(),
        price: Number(String(match[2]).replace(",", ".")),
        currency: String(match[3] ?? "SEK").toLowerCase() === "kr" ? "SEK" : String(match[3] ?? "SEK").toUpperCase()
      };
    });
}

function titleCase(value: string): string {
  return value.replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}
